### ISSUE TITLE
Integrating kerl with curl

### ISSUE THREAD

**Issue by crypto5000** [danilind/iota-web-wallet#10]
Hi Daniel, I hope all is well. 

I'm still coding out the voting project and (as mentioned previously in the iota.lib.js repo) I'm using your approach/code for the iota transfer wrapper. With the latest upgrade, I'm now trying to make sure that kerl is implemented correctly with your approach.

According to https://github.com/iotaledger/kerl, the signing now uses kerl (instead of curl). It seems that the new iota.lib.js now has the kerl code added for the prepareTransfer step. So, it seems that if I just replace the old iota.lib.js with the updated version, the signing should be handled properly. Does this seem correct or am I missing something?

The local proof of work still seems to be using curl. I'm not 100 percent sure of the full logic in your attachToTangle function, but it seems to be unaffected by the new kerl implementation? Is this correct? So, in summary, updating the iota.lib.js is required and the code (as is) should then work post-the-last-snapshot?

Any thoughts or help is appreciated.

**Comment by danilind** [comment]
Hi.
I have not gotten around to work on this yet, but I believe what you just wrote is accurate. Only the prepareTransfers call, and possibly everything that has to do with generating addresses, has been affected, so updating to the latest library should be sufficient

**Comment by crypto5000** [comment]
Thanks. This appears to work. Just sent a transfer through using your approach with kerl. The transaction is still pending but should confirm in normal time.

I'm trying to optimize the proof of work experience. The main drawbacks: 1) Chrome doesn't enable webgl2 by default, but Firefox does; 2) it takes about 2 minutes to do the proof of work on my machine. I'm thinking of trying to maybe use AWS Lambda to offload the proof of work and to prevent browser webgl2 issues. Have you looked into this?

Finally, quick question: do you know if it's possible to decipher the seed from the trytes returned in prepareTransfer? In other words, is it safe to transmit this object between server and client (not having the seed captured, if I don't want it exposed to the user)?

You can also close this issue to keep the repo clean whenever you want. Thanks again.

**Comment by danilind** [comment]
I have looked into outsourcing the pow to a remote server, but not using aws lambda. You can check out https://github.com/danilind/iota-wallet-curl to see my approach, it's just a plain websocket implementation in python using ccurl.
