### ISSUE TITLE
multiple new seeds to access single account

### ISSUE THREAD

**Issue by laurencefass** [danilind/iota-web-wallet#12]
im just testing this out on two computers... i seem to be able to access my account from two different computers using the same login name and new randomly generated seeds. is that right?

**Comment by danilind** [comment]
Hi.
First of all: Don't use the wallet, you risk loosing your funds.

Regarding your question, you will be able to access that same account is you use the same login information. If you use different seeds it's highly unlikely that you can access the same wallet. Keep in mind that you will be able to log in using any seed, but it will not be the same account unless the seeds are the same.

**Comment by laurencefass** [comment]
I didn't see this warning in the browser wallet. may it be a good idea to display to the user until such time its stable? id always run a test payment first, but probably not speaking for a large number of gung-ho users who may transfer and then regret later...

**Comment by laurencefass** [comment]
re my question: does this mean i can repeat the same user name with multiple different seeds? that would be convenient.

**Comment by danilind** [comment]
There is already a warning, telling users to move to a different wallet. I have now also disabled every aspect of the wallet, except seed recovery for existing users.

It's was possible to have multiple seeds in a single wallet/user. I considered adding the options, but never got around to do it.
