### ISSUE TITLE
plain-text seed backup file not stated clearly + feature request

### ISSUE THREAD

**Issue by alon-e** [danilind/iota-web-wallet#3]
>This will download your seed as a text file. Keep it somewhere safe

the wording on "backup" isn't explicit enough
backup should explicitly say the seed is saved *un-encrypted*

also an option to download an encrypted version of the seed (AES as done on server-side)
would be great, users are used to having a UTC / JSON file that they store safely - but not secretly.

this should be the default setting.

**Comment by danilind** [comment]
Done. Will be included in the next release
