### ISSUE TITLE
using data URI leaves traces

### ISSUE THREAD

**Issue by alon-e** [danilind/iota-web-wallet#4]
I like the use of `data:text/plain` , so you don't actually create a file on the server side.
but this leaves traces in browser download history:
![image](https://user-images.githubusercontent.com/25587995/28344998-de056a00-6c2f-11e7-9331-922508b3ce6e.png)

this, together with #3 (plain-text seed backup file) emphasizes the need for encrypted backups in my mind.

**Comment by danilind** [comment]
Done. Will be included in the next release
