### ISSUE TITLE
negative value transfers are "allowed"

### ISSUE THREAD

**Issue by alon-e** [danilind/iota-web-wallet#5]
```Please confirm sending -1 000 000 IOTAs to PRADUTNZ99BATVWNMCEHTUXATWVLTPVCQQBJYDIAHPQDAQDDQELWKS9PLHTCLNJYVB9ENJAINLQWOFVLXTHAHMKKFF```

The wallet allows a user to send negative values:
UI gets stuck on "preparing transaction"
![image](https://user-images.githubusercontent.com/25587995/28345538-b288cb02-6c33-11e7-8f5e-a355238186cc.png)

*setting negative values is also allowed with the up/down icons

**Comment by danilind** [comment]
Done. Will be included in the next release
