### ISSUE TITLE
require_first_time_proof should ask for client consent

### ISSUE THREAD

**Issue by alon-e** [danilind/iota-web-wallet#6]
even though `require_first_time_proof` is only used as a temporary workaround: 
[app/controllers/wallets_controller.rb#L160](https://github.com/danilind/iota-web-wallet/blob/311f7c5d8e950f4eb4ca3ba7dd29d94d7fd95587/app/controllers/wallets_controller.rb#L160)

it gives the server-side the ability to request a user's `password` & automatically receive it.
the actual code running in production is unknown & may be altered over time (w/ or w/o developer's knowledge).

I propose 2 things:
1. ask for user's consent before running [app/assets/javascripts/wallet/user_ui.js#L187](https://github.com/danilind/iota-web-wallet/blob/42d3f00344bbb8ec5dab2a3baced659fd249494a/app/assets/javascripts/wallet/user_ui.js#L187)
2. commit to a date when this workaround will be removed.
(do you still have users in the DB w/o the password hash?)

**Comment by danilind** [comment]
Done. Will be included in the next release
