### ISSUE TITLE
Incorrect balance

### ISSUE THREAD

**Issue by jurjendevries** [danilind/iota-web-wallet#7]
After 3 transactions  (200 Mi in, 200 Mi out, 200 Mi in) it gives me a balance of 0, while I expect 200 Mi. See this screenshot:

![iota wallet balance](https://user-images.githubusercontent.com/355488/28357011-4d18a166-6c6a-11e7-9255-b266c0806347.png)

http://iota.tips/search/?kind=address&hash=PNMGNQCYJOSERPXKH9JXMN9CQCTWXNSEVFLOWPLYYIEDQAMXXFBVOPLGYBPYYHDPPVLKXYYEOLSAVXAWYBTUQQSVRS is displaying the correct balance.

I have to say that the latest transaction was still pending after 25 minutes, so I used the re-attach button, and then after a few minutes it was completed.

Things I tried to resolve to get the correct balance in the wallet:
- Browser Refresh
- Logout / Login
- Clicking 'Load all' link

Computer info:
Chome OS Version 59.0.3071.91 (Official Build) (64-bit)

**Comment by danilind** [comment]
Hi. Could you post a screenshot of the addresses? Press the three dots go get to it

**Comment by jurjendevries** [comment]
Hi, here is the screenshot. It only shows the address that I have given in the url in my first post.

![iota wallet](https://user-images.githubusercontent.com/355488/28485871-f88a4fa4-6e7c-11e7-857e-a5032af3099f.png)

**Comment by danilind** [comment]
Found the error, it will be fixed in the next release. Thanks for reporting it.

**Comment by jurjendevries** [comment]
Thanks for fixing 👍
