### ISSUE TITLE
Requested feature: offline address generation

### ISSUE THREAD

**Issue by mrstormlars** [danilind/iota-web-wallet#8]
Hi,

I'm missing a feature that is not present in any IOTA wallet atm: tools for cold storage. Ideally, it should be possible to download a copy of the iota web wallet and install it on an air-gapped computer. The following tools are wanted (in decreasing order of priority):
1. Offline address generation. (There is this tool: http://148.251.233.147/AdderesGenerator.zip, but it doesn't generate the last 9 characters of checksum. There is also this paper wallet: https://www.dropbox.com/s/tx6ac7zb196gmfy/iotapaper.zip?dl=0, but it currently doesn't output an address that is possible to copy&paste).
2. A random seed generator (that works offline). 
3. If possible: a way to sign transactions offline (as is possible with myetherwallet for Eth.).

**Comment by danilind** [comment]
Hi.
This is a online wallet, so I'm not sure if this is the right place to implement those features. If you are familiar with programming I can help you with 1 and 2. If not you can visit the developer channel in the slack and ask if anyone is interested in making it. 

3 would be possible, but I'm not really sure if I see the security benefits of it unless the hardware is custom made.

**Comment by mrstormlars** [comment]
Hi, I'm not very familiar with programming. However, providing an easy and secure way for users to store their IOTAs offline should be prioritized. I believe a lot of IOTA is stored at Bitfinex right now, and in the event of a hack, that could be devastating for IOTA... 
I'm maybe spoiled by having used MyEtherWallet for ETH and tokens. They are building a client-side wallet that is used through the browser. I thoght you were doing almost the same. Check https://github.com/kvhnuke/etherwallet. They have an offline option, which works like a charm... :-)
PS: Hardware wallet is off course even better! Ledger?

**Comment by mrstormlars** [comment]
I now see that @arancauchi has added the functionality to copy/paste the generated address in the the paper wallet (https://arancauchi.github.io/IOTA-Paper-Wallet/). That will serve my needs. Case closed.
